# Generated by Django 4.2.30 on 2026-04-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_package_packagepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='sslcommerz_tran_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='sslcommerz_val_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
