# Generated by Django 4.2.30 on 2026-04-15 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0003_packagepurchase_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after quiz submission to explain the correct answer.'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for image-based questions.', null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice (Single Answer)'), ('multi', 'Multiple Choice (Multiple Answers)'), ('tf', 'True / False'), ('short', 'Short Answer')], default='mcq', help_text='Type of question.', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='short_answer_text',
            field=models.CharField(blank=True, help_text='Correct answer for short-answer questions (case-insensitive match).', max_length=500),
        ),
        migrations.AddField(
            model_name='quiz',
            name='per_question_time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-question time limit in seconds. Leave blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_instant_feedback',
            field=models.BooleanField(default=False, help_text='Show correct answer immediately after selecting a choice.'),
        ),
        migrations.CreateModel(
            name='BookmarkedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
