# Generated by Django 4.2.30 on 2026-06-06 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0004_question_explanation_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_fee_per_sale', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee the platform keeps on each vendor sale. The vendor earns (sale price − this fee).', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='QuizPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('sslcommerz_val_id', models.CharField(blank=True, max_length=200)),
                ('sslcommerz_tran_date', models.CharField(blank=True, max_length=100)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The vendor who created this category. Empty for admin-created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Vendor-created categories require admin approval before going public.'),
        ),
        migrations.AddField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The vendor who owns this package. Empty for platform/admin-owned packages.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved / Published'), ('rejected', 'Rejected')], default='draft', help_text='Review workflow status. Admin approval sets this to "approved".', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The vendor who owns this quiz. Empty for platform/admin-owned quizzes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price to purchase this quiz individually. 0 means free/open.', max_digits=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved / Published'), ('rejected', 'Rejected')], default='draft', help_text='Review workflow status. Admin approval sets this to "approved" and publishes the quiz.', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('quiz', 'Quiz'), ('package', 'Package')], max_length=10)),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot of the platform fee at the time of sale.', max_digits=10)),
                ('vendor_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_sales', to='quizzes.package')),
                ('package_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_sale', to='quizzes.packagepurchase')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_sales', to='quizzes.quiz')),
                ('quiz_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_sale', to='quizzes.quizpurchase')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-folder-fill', help_text='Bootstrap icon class, e.g. bi-folder-fill', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Vendor-created subcategories require admin approval before going public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subcategories', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quizzes.department')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quizpurchase',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quizpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quizzes.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='quizpurchase',
            unique_together={('user', 'quiz')},
        ),
    ]
