# Generated by Django 4.2.30 on 2026-06-06 10:12

from django.db import migrations


def backfill(apps, schema_editor):
    Department = apps.get_model('quizzes', 'Department')
    Quiz = apps.get_model('quizzes', 'Quiz')
    Package = apps.get_model('quizzes', 'Package')
    PlatformSetting = apps.get_model('quizzes', 'PlatformSetting')

    # Existing categories are admin-created — keep them visible.
    Department.objects.update(is_approved=True)

    # Existing published quizzes are live → approved; the rest stay as drafts.
    Quiz.objects.filter(is_published=True).update(status='approved')
    Quiz.objects.filter(is_published=False).update(status='draft')

    # Existing packages are admin-owned and live → approved.
    Package.objects.update(status='approved')

    # Ensure the singleton settings row exists.
    PlatformSetting.objects.get_or_create(pk=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_platformsetting_quizpurchase_department_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
